import { defineConfig } from 'vite';
import { resolve } from 'path';

export default defineConfig({
  base: '/devkit/',
  root: '.',
  build: {
    outDir: 'dist',
    emptyOutDir: true,
    rollupOptions: {
      input: {
        root: resolve(__dirname, 'index.html'),
        main: resolve(__dirname, 'pages/index.html'),
        json: resolve(__dirname, 'pages/json/index.html'),
        base64: resolve(__dirname, 'pages/base64/index.html'),
        'url-codec': resolve(__dirname, 'pages/url-codec/index.html'),
        jwt: resolve(__dirname, 'pages/jwt/index.html'),
        regex: resolve(__dirname, 'pages/regex/index.html'),
        timestamp: resolve(__dirname, 'pages/timestamp/index.html'),
        uuid: resolve(__dirname, 'pages/uuid/index.html'),
        hash: resolve(__dirname, 'pages/hash/index.html'),
        color: resolve(__dirname, 'pages/color/index.html'),
        markdown: resolve(__dirname, 'pages/markdown/index.html'),
        cron: resolve(__dirname, 'pages/cron/index.html'),
        'text-diff': resolve(__dirname, 'pages/text-diff/index.html'),
        'code-formatter': resolve(__dirname, 'pages/code-formatter/index.html'),
        'sql-formatter': resolve(__dirname, 'pages/sql-formatter/index.html'),
        password: resolve(__dirname, 'pages/password/index.html'),
        'number-base': resolve(__dirname, 'pages/number-base/index.html'),
        'unit-converter': resolve(__dirname, 'pages/unit-converter/index.html'),
        yaml: resolve(__dirname, 'pages/yaml/index.html'),
        'image-compress': resolve(__dirname, 'pages/image-compress/index.html'),
        'image-format': resolve(__dirname, 'pages/image-format/index.html'),
        qrcode: resolve(__dirname, 'pages/qrcode/index.html'),
        countdown: resolve(__dirname, 'pages/countdown/index.html'),
        bmi: resolve(__dirname, 'pages/bmi/index.html'),
        random: resolve(__dirname, 'pages/random/index.html'),
        'case-converter': resolve(__dirname, 'pages/case-converter/index.html'),
        'text-dedupe': resolve(__dirname, 'pages/text-dedupe/index.html'),
        'html-entity': resolve(__dirname, 'pages/html-entity/index.html'),
        toml: resolve(__dirname, 'pages/toml/index.html'),
        'word-counter': resolve(__dirname, 'pages/word-counter/index.html'),
        'age-calculator': resolve(__dirname, 'pages/age-calculator/index.html'),
        'date-diff': resolve(__dirname, 'pages/date-diff/index.html'),
        'interest': resolve(__dirname, 'pages/interest/index.html'),
        'csv-viewer': resolve(__dirname, 'pages/csv-viewer/index.html'),
        'prepayment': resolve(__dirname, 'pages/prepayment/index.html'),
        'image-resize': resolve(__dirname, 'pages/image-resize/index.html'),
        'tax': resolve(__dirname, 'pages/tax/index.html'),
        'watermark': resolve(__dirname, 'pages/watermark/index.html'),
        'favicon': resolve(__dirname, 'pages/favicon/index.html'),
        'unicode': resolve(__dirname, 'pages/unicode/index.html'),
        'lorem': resolve(__dirname, 'pages/lorem/index.html'),
        'encrypt': resolve(__dirname, 'pages/encrypt/index.html'),
        'gradient': resolve(__dirname, 'pages/gradient/index.html'),
        'id-photo': resolve(__dirname, 'pages/id-photo/index.html'),
        'collage': resolve(__dirname, 'pages/collage/index.html'),
        'img-to-pdf': resolve(__dirname, 'pages/img-to-pdf/index.html'),
        'currency': resolve(__dirname, 'pages/currency/index.html'),
        'calendar': resolve(__dirname, 'pages/calendar/index.html'),
        'signature': resolve(__dirname, 'pages/signature/index.html'),
        'chart': resolve(__dirname, 'pages/chart/index.html'),
        'invoice': resolve(__dirname, 'pages/invoice/index.html'),
        'placeholder': resolve(__dirname, 'pages/placeholder/index.html'),
        'json-schema': resolve(__dirname, 'pages/json-schema/index.html'),
        'tts': resolve(__dirname, 'pages/tts/index.html'),
        'timer': resolve(__dirname, 'pages/timer/index.html'),
        'grid-splitter': resolve(__dirname, 'pages/grid-splitter/index.html'),
        'http-tester': resolve(__dirname, 'pages/http-tester/index.html'),
        'pomodoro': resolve(__dirname, 'pages/pomodoro/index.html'),
        'random-picker': resolve(__dirname, 'pages/random-picker/index.html'),
        'box-shadow': resolve(__dirname, 'pages/box-shadow/index.html'),
        'spin-wheel': resolve(__dirname, 'pages/spin-wheel/index.html'),
        'cover-maker': resolve(__dirname, 'pages/cover-maker/index.html'),
        'emoji-search': resolve(__dirname, 'pages/emoji-search/index.html'),
        'screen-recorder': resolve(__dirname, 'pages/screen-recorder/index.html'),
        'pdf-merge': resolve(__dirname, 'pages/pdf-merge/index.html'),
        'pdf-split': resolve(__dirname, 'pages/pdf-split/index.html'),
        'pdf-compress': resolve(__dirname, 'pages/pdf-compress/index.html'),
        'color-picker': resolve(__dirname, 'pages/color-picker/index.html'),
        'notepad': resolve(__dirname, 'pages/notepad/index.html'),
        'ip-lookup': resolve(__dirname, 'pages/ip-lookup/index.html'),
        'code-screenshot': resolve(__dirname, 'pages/code-screenshot/index.html'),
        'html-to-markdown': resolve(__dirname, 'pages/html-to-markdown/index.html'),
        'morse-code': resolve(__dirname, 'pages/morse-code/index.html'),
        'qr-scanner': resolve(__dirname, 'pages/qr-scanner/index.html'),
        'chinese-convert': resolve(__dirname, 'pages/chinese-convert/index.html'),
        'avatar-generator': resolve(__dirname, 'pages/avatar-generator/index.html'),
        'coord-convert': resolve(__dirname, 'pages/coord-convert/index.html'),
        'ua-parser': resolve(__dirname, 'pages/ua-parser/index.html'),
        'blood-type': resolve(__dirname, 'pages/blood-type/index.html'),
        'zodiac': resolve(__dirname, 'pages/zodiac/index.html'),
        'name-generator': resolve(__dirname, 'pages/name-generator/index.html'),
        'math-practice': resolve(__dirname, 'pages/math-practice/index.html'),
        'pinyin-practice': resolve(__dirname, 'pages/pinyin-practice/index.html'),
        'zipcode': resolve(__dirname, 'pages/zipcode/index.html'),
        'university': resolve(__dirname, 'pages/university/index.html'),
        'copybook': resolve(__dirname, 'pages/copybook/index.html'),
        'periodic-table': resolve(__dirname, 'pages/periodic-table/index.html'),
        'multiplication': resolve(__dirname, 'pages/multiplication/index.html'),
      },
    },
  },
});
